apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: loadbalancer 
  ports:
    - port: 8080
      targetPort: 8080
      name: "http"
    - port: 50000
      name: "slave"
      targetPort: 50000
  selector:
    app: jenkins