apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jenkins-sg
  namespace: jenkins
provisioner: kubernetes.io/gce-pd
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  volumeMode: Filesystem
  storageClassName: jenkins-sg
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
